### ISSUE TITLE
[BUG] 'target' of semantic segmentation loader doesn't match with class number

### ISSUE THREAD

**Issue by illian01** [Nota-NetsPresso/netspresso-trainer#150]
### Describe the bug

In [SegmentationCustomDataset](https://github.com/nota-github/netspresso-trainer-dev/blob/dev/src/netspresso_trainer/dataloaders/segmentation/local.py) line 35, label is read with PIL.
If I extract unique value of the label, I can get the below like array.
```
np.unique(np.array(label))
> array([  0, 147, 151, 220], dtype=uint8)
```
Even when the label passes through transform function (line 44), it still has large values.
```
out['mask'].unique()
> tensor([0, 151, 220])
```
It causes error when trainer try to compute loss (Cross entropy), because the model has 21 classes (including background) not over 200 classes.
The dataset have to convert mask pixel intensity to class values.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

I downloaded [VOC2012](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/) datasets, and executed instruction below.

`python ./train.py --data config/data/voc12.yaml --augmentation config/augmentation/segmentation.yaml --model config/model/segformer/segformer-segmentation.yaml --training config/training/segmentation.yaml --logging config/logging.yaml --environment config/environment.yaml`

### Logs

```shell
(np_trainer) junho.shin@3090e:~/netspresso-trainer-dev$ python ./train.py --data config/data/voc12.yaml --augmentation config/augmentation/segmentation.yaml --model config/model/segformer/segformer-segmentation.yaml --training config/training/segmentation.yaml --logging config/logging.yaml --environment config/environment.yaml
2023-09-12_14:53:39 KST | INFO          | trainer:<trainer_common.py>:107 >>> Task: segmentation | Model: segformer | Training with torch.fx model? False
2023-09-12_14:53:39 KST | INFO          | build_dataset:<builder.py>:16 >>> ----------------------------------------
2023-09-12_14:53:39 KST | INFO          | build_dataset:<builder.py>:17 >>> Loading data...
2023-09-12_14:53:39 KST | INFO          | build_dataset:<builder.py>:88 >>> Summary | Dataset: <voc2012> (with local format)
2023-09-12_14:53:39 KST | INFO          | build_dataset:<builder.py>:89 >>> Summary | Training dataset: 1464 sample(s)
2023-09-12_14:53:39 KST | INFO          | build_dataset:<builder.py>:91 >>> Summary | Validation dataset: 1449 sample(s)
2023-09-12_14:53:41 KST | INFO          | train:<base.py>:150 >>> ----------------------------------------
  0%|                                                                                                                                                                     | 0/183 [00:00<?, ?it/s]../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [10,0,0], thread: [416,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [10,0,0], thread: [417,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [10,0,0], thread: [418,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [10,0,0], thread: [419,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [10,0,0], thread: [420,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [800,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [801,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [802,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [803,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [804,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [805,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [806,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [807,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [928,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [929,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [930,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [931,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [932,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [288,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [289,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [290,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [291,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [292,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [13,0,0], thread: [293,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [448,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [449,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [450,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [451,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [452,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [453,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [280,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [281,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [282,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [283,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [284,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [285,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [286,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [287,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [480,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [11,0,0], thread: [735,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [128,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [129,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [130,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [131,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [132,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [133,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [134,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [694,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [695,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [696,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [697,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [698,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [699,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [700,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [701,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [702,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [703,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [3,0,0], thread: [91,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [3,0,0], thread: [92,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [3,0,0], thread: [93,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [3,0,0], thread: [94,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [3,0,0], thread: [95,0,0] Assertion `t >= 0 && t < n_classes` failed.
2023-09-12_14:53:43 KST | ERROR         | train:<base.py>:201 >>> CUDA error: device-side assert triggered                                                                                        
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "./train.py", line 5, in <module>
    trainer(is_graphmodule_training=False)
  File "/ssd1/junho.shin/netspresso-trainer-dev/src/netspresso_trainer/trainer_common.py", line 146, in trainer
    raise e
  File "/ssd1/junho.shin/netspresso-trainer-dev/src/netspresso_trainer/trainer_common.py", line 139, in trainer
    trainer.train()
  File "/ssd1/junho.shin/netspresso-trainer-dev/src/netspresso_trainer/pipelines/base.py", line 202, in train
    raise e
  File "/ssd1/junho.shin/netspresso-trainer-dev/src/netspresso_trainer/pipelines/base.py", line 162, in train
    self.train_one_epoch()
  File "/ssd1/junho.shin/netspresso-trainer-dev/src/netspresso_trainer/pipelines/base.py", line 206, in train_one_epoch
    self.train_step(batch)
  File "/ssd1/junho.shin/netspresso-trainer-dev/src/netspresso_trainer/pipelines/segmentation.py", line 39, in train_step
    self.loss_factory.backward()
  File "/ssd1/junho.shin/netspresso-trainer-dev/src/netspresso_trainer/losses/builder.py", line 54, in backward
    self.total_loss_for_backward.mean().backward()
  File "/ssd1/junho.shin/anaconda3/envs/np_trainer/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/ssd1/junho.shin/anaconda3/envs/np_trainer/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by deepkyu** [comment]
The internal VOC dataset that I used in testing semantic segmentation turns out `L` format mask labels.
![image](https://github.com/Nota-NetsPresso/netspresso-trainer/assets/39237606/2a73ef5a-3314-464b-b10e-11ad0430df1a)

I'll fix it ASAP

**Comment by deepkyu** [comment]
Hi @illian01 ,

could you share the mapping dict between RGB value : VOC12 class?
I need to double-check for my newly updated VOC12 dataset config.

**Comment by illian01** [comment]
@deepkyu 

Here is the palette that can be attained by loading mask image.

```
img = Image.open(./data/VOC2012/mask/val/2007_000033.png')
print(img.palette.colors)
> {(0, 0, 0): 0, 
(128, 0, 0): 1, 
(0, 128, 0): 2, 
(128, 128, 0): 3, 
(0, 0, 128): 4, 
(128, 0, 128): 5, 
(0, 128, 128): 6, 
(128, 128, 128): 7, 
(64, 0, 0): 8, 
(192, 0, 0): 9, 
(64, 128, 0): 10,
(192, 128, 0): 11, 
(64, 0, 128): 12, 
(192, 0, 128): 13, 
(64, 128, 128): 14, 
(192, 128, 128): 15, 
(0, 64, 0): 16, 
(128, 64, 0): 17, 
(0, 192, 0): 18, 
(128, 192, 0): 19, 
(0, 64, 128): 20, 
(128, 64, 128): 21, 
(0, 192, 128): 22,
...
(224, 224, 192): 255}
```

**Comment by deepkyu** [comment]
@illian01 Confirmed. Thx 👍🏻
